ALTER TABLE apartments ADD COLUMN created_by VARCHAR(60) NOT NULL DEFAULT 'system';
ALTER TABLE apartments ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE apartments ADD COLUMN updated_by VARCHAR(60);
ALTER TABLE apartments ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE apartments ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE apartments ADD COLUMN deleted_by VARCHAR(60);
ALTER TABLE apartments ADD COLUMN deleted_at TIMESTAMP;

ALTER TABLE residents ADD COLUMN created_by VARCHAR(60) NOT NULL DEFAULT 'system';
ALTER TABLE residents ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE residents ADD COLUMN updated_by VARCHAR(60);
ALTER TABLE residents ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE residents ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE residents ADD COLUMN deleted_by VARCHAR(60);
ALTER TABLE residents ADD COLUMN deleted_at TIMESTAMP;

ALTER TABLE payments ADD COLUMN created_by VARCHAR(60) NOT NULL DEFAULT 'system';
ALTER TABLE payments ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE payments ADD COLUMN updated_by VARCHAR(60);
ALTER TABLE payments ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE payments ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE payments ADD COLUMN deleted_by VARCHAR(60);
ALTER TABLE payments ADD COLUMN deleted_at TIMESTAMP;
